[package]
name = "antigen-rapier3d"
version = "0.1.0"
edition = "2021"

[dependencies]
rapier3d = "0.11.1"
hecs = "0.7.3"
nalgebra = "0.30.1"
parking_lot = "0.11.2"

antigen-core = { path = "../antigen-core" }
